name: Pipeline

on: [push]

jobs:
  build:
    name: "Lint and Test"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_ENABLE_TELEMETRY: true

    steps:
      - uses: actions/checkout@v3

      - name: Cache Batect
        uses: actions/cache@v2
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Check formatting
        run: ./batect check-format

      - name: Lint code
        run: ./batect lint

      - name: Test bundle
        run: ./batect test
